# Generated by Django 3.2.5 on 2021-09-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210902_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
    ]
