# Generated by Django 3.2.5 on 2021-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_contacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
