# Generated by Django 3.2.5 on 2021-09-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_contacts_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='message',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='business_field',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='lastName',
        ),
    ]
